import type { AgentAction } from "@/types"

export const DEMO_ACTIONS: AgentAction[] = [
  {
    id: "act-001",
    brandId: "demo",
    agent: "acquisition",
    type: "pause_campaign",
    title: "Pause Meta Prospecting — Lookalike 1% Mumbai (negative CM 9 days)",
    description: "This campaign has generated ₹2.18 in revenue per ₹1 of ad spend over the last 9 days, but after channel fees, shipping, and COGS, the contribution margin per rupee spent (CMPR) is -0.04. It's actively destroying margin.",
    expectedImpact: 38400,
    expectedImpactPct: 1.1,
    confidence: 0.91,
    status: "pending",
    permissionLevel: "propose",
    reasoning: "7-day rolling CMPR is -0.04 (target: ≥0.22). Campaign has spent ₹1,24,000 in the last 9 days with only 38 conversions at ₹3,263 CPA. Product AOV is ₹847. First-order CM is negative. The audience is saturated — CTR has declined 38% in 14 days. Pausing will save ₹38,400/month in negative-margin spend.",
    data: {
      campaignId: "MC-001-A",
      platform: "meta",
      currentDailySpend: 13800,
      roas7d: 2.18,
      cmpr7d: -0.04,
      ctrTrend: -0.38,
    },
    createdAt: new Date(Date.now() - 3600000),
    executedAt: null,
  },
  {
    id: "act-002",
    brandId: "demo",
    agent: "quick_commerce",
    type: "replenishment",
    title: "Replenish Vitamin C Serum at Blinkit Koramangala — 2 days stock remaining",
    description: "Dark store Koramangala-07 has 23 units of Vitamin C Serum 30ml remaining. At current DRR of 11 units/day, stockout will occur in approximately 48 hours, wiping ₹91,000 in estimated monthly Q-commerce revenue from this location.",
    expectedImpact: 91000,
    expectedImpactPct: 2.6,
    confidence: 0.97,
    status: "pending",
    permissionLevel: "propose",
    reasoning: "Current inventory: 23 units. 14-day DRR: 10.8 units/day. Days of stock: 2.1. This is a priority SKU with 34% CM on Blinkit. Recommended replenishment: 200 units (18-day coverage). Mother warehouse stock confirmed: 847 units available. Logistics lead time to dark store: 18-24 hours.",
    data: {
      darkStore: "Blinkit-Koramangala-07",
      currentStock: 23,
      dailyRunRate: 10.8,
      daysOfStock: 2.1,
      recommendedQty: 200,
      warehouseStock: 847,
    },
    createdAt: new Date(Date.now() - 1800000),
    executedAt: null,
  },
  {
    id: "act-003",
    brandId: "demo",
    agent: "margin_analyst",
    type: "cod_intervention",
    title: "Enable WhatsApp COD Verification for Orders from 5 High-RTO Pincodes",
    description: "5 pincodes (482001, 831001, 263001, 226003, 400097) collectively account for 23% of your total RTO events despite only 11% of orders. Enabling pre-dispatch WhatsApp confirmation for these pincodes can reduce RTO by 40-55% in this cohort.",
    expectedImpact: 67200,
    expectedImpactPct: 1.9,
    confidence: 0.83,
    status: "pending",
    permissionLevel: "propose",
    reasoning: "Analysis of last 90 days: pincodes 482001, 831001, 263001, 226003, 400097 have combined RTO rate of 38.4% on COD orders (vs 12.1% brand average). Monthly RTO loss from these 5 pincodes: approximately ₹1.68 lakh (freight forward + freight reverse + inventory damage). Industry data suggests WhatsApp pre-confirmation reduces RTO by 40-55%. Conservative estimate: ₹67,200/month savings at 40% reduction.",
    data: {
      pincodes: ["482001", "831001", "263001", "226003", "400097"],
      combinedRtoRate: 0.384,
      monthlyRtoLoss: 168000,
      projectedSavings: 67200,
    },
    createdAt: new Date(Date.now() - 7200000),
    executedAt: null,
  },
  {
    id: "act-004",
    brandId: "demo",
    agent: "acquisition",
    type: "increase_budget",
    title: "Increase Google Brand Search budget by 20% (CMPR 1.84 — best in portfolio)",
    description: "Your Brand Search campaign on Google has a 7-day CMPR of 1.84 — the highest in your acquisition portfolio. It's impression-share constrained at 73%. Increasing daily budget by 20% (₹4,400/day) should capture 15-18% more impression share with similar efficiency.",
    expectedImpact: 52800,
    expectedImpactPct: 1.5,
    confidence: 0.87,
    status: "pending",
    permissionLevel: "propose",
    reasoning: "GC-001 Brand Search: 7d CMPR 1.84 (target 0.22), impression share 73.2%, lost IS (budget) 18.4%, lost IS (rank) 8.4%. Current daily budget: ₹22,000. Proposed: ₹26,400 (+₹4,400/day). At current efficiency, incremental ₹1,32,000/month in spend is projected to generate ₹2,43,000 in revenue and ₹52,800 in additional CM.",
    data: {
      campaignId: "GC-001",
      platform: "google",
      currentDailyBudget: 22000,
      proposedDailyBudget: 26400,
      impressionShare: 73.2,
      cmpr7d: 1.84,
    },
    createdAt: new Date(Date.now() - 10800000),
    executedAt: null,
  },
  {
    id: "act-005",
    brandId: "demo",
    agent: "margin_analyst",
    type: "pricing",
    title: "Review Niacinamide Toner pricing — 11.4% CM below category floor",
    description: "Niacinamide Toner 100ml is generating 11.4% contribution margin — 8.6 percentage points below your category minimum of 20%. MRP is ₹449 but heavy discounting on Amazon (avg 22% off) is compressing margins below sustainability threshold.",
    expectedImpact: 44100,
    expectedImpactPct: 1.2,
    confidence: 0.79,
    status: "pending",
    permissionLevel: "notify",
    reasoning: "30d analysis: Niacinamide Toner CM% = 11.4% (threshold: 20%). Revenue: ₹3,67,500. Margin: ₹41,895. If sold at same volume with 0% discount (eliminating Amazon promo), CM% would be 21.6%. Discount cost this month: ₹80,850. Recommendation: either raise MRP to ₹549 (competitive with Minimalist, Dot & Key) or cap Amazon discount at 10%. Whichever direction, document the trade-off in pricing review.",
    data: {
      sku: "GNB-NAT-100",
      currentCMPct: 11.4,
      targetCMPct: 20,
      avgDiscount: 0.22,
      monthlyDiscountCost: 80850,
    },
    createdAt: new Date(Date.now() - 14400000),
    executedAt: null,
  },
]
